<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no">
    <title>Home</title>
</head>

<body>
    <header>
        <?php require_once $config["VIEW_PATH"] . 'layout' . DS . 'layout.phtml'; ?>
    </header>

    <article>

        <div class="art-A">


            <h1 class="txt-A">Vet Cooling System</h1>

            <p class="txt-B">Heating, Ventilating & Air Conditioning Service</p>
            <br>
            <p class="txt-C">Service & Maintenance</p>

            <p class="txt-C">Keep your air-conditioning unit running at optimal performance all year round!</p>
            <br>
            <button class="button-B" onclick="location.href='?page=customer_area'">Customer Area</button>
        </div>

        <br>


        <div class="art-B">

            <p class="txt-D"><span><img src="<?php echo $config["IMG_PATH"] . 'offer.png'; ?>" class="icons" alt=""></span> &nbsp; Vet Cooling is offering you the following services</p>
            <ul class="txt-A1">
                <li>General Cleaning all types of Aircon</li>
                <br>
                <li>Survey, Estimate, & Install</li>
                <br>
                <li>Repair Ref & Aircon</li>
                <br>
            </ul>

        </div>
        <div class="art-B">

            <p class="txt-D"><span><img src="<?php echo $config["IMG_PATH"] . 'tools.png'; ?>" class="icons" alt=""></span> &nbsp; Repair & Cleaning (All type's of Air-conditioning)</p>
            <ul class="txt-A1">
                <li>Window Air Conditioners</li>
                <br>
                <li>Ceiling Cassette Air Conditioners</li>
                <br>
                <li>Portable Air Conditioners</li>
                <br>
                <li>Ductless Split System Air Conditioners</li>
                <br>
                <li>Floor Mounted Air Conditioners</li>
                <br>
            </ul>

        </div>

        <div class="art-B">

            <p class="txt-D"><span><img src="<?php echo $config["IMG_PATH"] . 'call.png'; ?>" class="icons" alt=""></span> &nbsp; For Inquiries call now @</p>
            <ul class="txt-A1">
                <li>420-9434/421-1621</li>
                <br>
                <li>S09420727142</li>
                <br>

            </ul>

        </div>

        <div class="art-B">

            <p class="txt-D"><span><img src="<?php echo $config["IMG_PATH"] . 'location.png'; ?>" class="icons" alt=""></span> &nbsp; Location</p>
            <ul class="txt-A1">
                <li>Romero Bldg. North Road Hi-way Basak Mandaue City 6014 Mandaue City, Philippines</li>
                <br>
                <a href="https://www.google.com/maps/dir/10.3251968,123.9220224/10.35242,123.94422/@10.3367067,123.917599,14z/data=!3m1!4b1!4m4!4m3!1m1!4e1!1m0">Go to Google Maps</a>
                <br>
            </ul>

        </div>

        <div class="art-B">

            <p class="txt-D"><span><img src="<?php echo $config["IMG_PATH"] . 'email.png'; ?>" class="icons" alt=""></span> &nbsp; Email</p>
            <ul class="txt-A1">
                <li>vetcooling@gmail.com</li>
                <br>
            </ul>

        </div>

        <div class="art-B">

            <p class="txt-D"><span><img src="<?php echo $config["IMG_PATH"] . 'open.png'; ?>" class="icons" alt=""></span> &nbsp; Open</p>
            <ul class="txt-A1">
                <li style="color:green">Always Open</li>
                <br>
            </ul>

        </div>

        <div class="art-B">

            <p class="txt-D"><span><img src="<?php echo $config["IMG_PATH"] . 'facebookIcon.png'; ?>" class="icons" alt=""></span> &nbsp; Follow us on Facebook</p>
            <ul class="txt-A1">
                <a href="https://www.facebook.com/airconsystem">Go to Facebook</a>
                <br>
            </ul>
            <br>
        </div>




    </article>

    <footer>

        <div class="div_footer">

            <p class="txtCopyright">© Copyright - Vet Cooling System 2021</p>
        </div>
    </footer>
</body>

</html>