<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <title>Home</title>
    
</head>
<body>

<article>
   <div class="div_Body" >

   <div class="fltNav"><?php require $config["VIEW_PATH"]. "layout". DS . "layout.phtml"; ?></div>
    <img class="imgCover" src="<?php echo $config["IMG_PATH"]. 'cover.jpg';?>" alt="">

    <h1 class="fltCenter">Vet Cooling System </h1>
   
    <p class="fltCenter1"> Heating, Ventilating & Air Conditioning Service</p>
   <div class="fltLeft">Service & Maintenance</div>
  
   <div class="fltLeft_1">Keep your air-conditioning unit running at optimal performance all year round!</div>
  
   </div>


    <br><br>



    <div>
   
    <h1 class="txtC2"> &nbsp;<span>  <img class="" src="<?php echo $config["IMG_PATH"]. 'offer.png';?>" alt=""></span> Vet Cooling is offering you the following services</h1>
     <ul class="txtC3">
        <li><p >General Cleaning all types of Aircon</p></li>
        <li><p>Survey, Estimate, & Install</p></li>
        <li><p>Repair Ref & Aircon</p></li>
     </ul>
    </div>
     <br>
    <div >

    <h1 class="txtC2"> &nbsp;<span>  <img class="" src="<?php echo $config["IMG_PATH"]. 'call.png';?>" alt=""></span> For Inquiries call now @ </h1>
     <ul class="txtC3">
        <li><p >420-9434/421-1621</p></li>
        <li><p>09420727142</p></li>
        
      </ul>
    </div>
    <br>

    <div>

    <h1 class="txtC2"> &nbsp;<span>  <img class="" src="<?php echo $config["IMG_PATH"]. 'location.png';?>" alt=""></span> Location</h1>
    <ul class="txtC3">
      
    <li><p >Romero Bldg. North Road Hi-way Basak Mandaue City 6014 Mandaue City, Philippines</p></li>
    <a href="https://www.google.com/maps/dir/10.3251968,123.9220224/10.35242,123.94422/@10.3367067,123.917599,14z/data=!3m1!4b1!4m4!4m3!1m1!4e1!1m0">Goto Google Maps</a>
    </ul>
    </div>

    <br>
    <div >
   
    <h1 class="txtC2"> &nbsp;<span>  <img class="" src="<?php echo $config["IMG_PATH"]. 'email.png';?>" alt=""></span> Email</h1>
    <ul class="txtC3">
        <li><p >vetcooling@gmail.com</p></li>
        
    </ul>
    </div>
    <br>
    <div  >
    <h1 class="txtC2" style="color:green;"> &nbsp;<span>  <img class="" src="<?php echo $config["IMG_PATH"]. 'open.png';?>" alt=""></span> Always Open</h1>
  
    </div>
    <br>
    <div >

    <div class="div_Fb">
    
    <img src="<?php echo $config["IMG_PATH"]. 'facebook.png';?>" alt="" class="imgIconF" >
    <br>
    <br>
    <a href="https://www.facebook.com/airconsystem" style="font-size:5mm; font-family:arial; font-weight: bold;; margin-left:10px;" >Goto Facebook</a>
    </div>
    <ul class="txtC3">
       
        
    </ul>
    </div>
    <br><br><br><br><br><br>

</article>
   
    <footer>
    
    <div class="div_footer">
    
     <p class="txtCopyright">© Copyright - Vet Cooling System 2021</p>
    </div>

    </footer>
    
</body>

</html>