<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Settings</title>
    <link rel="stylesheet" href="<?php echo $config["LIB_PATH"] . 'css' . DS . 'style.css'; ?>">
    <link rel="stylesheet" href="<?php echo $config["LIB_PATH"] . 'css' . DS . 'style1.css'; ?>">
    <script src="<?php echo $config["LIB_PATH"] . 'js' . DS . 'replacestate.js'; ?>"></script>



    <title>Database</title>

    <style>
        .tbl-h {
            font-size: 4mm;
            font-family: arial;
            border-radius: 6px;
            border-style: none;
            outline-style: none;
            background-color: #045de9;
            font-weight: bold;
            color: white;
            width: 150px;


        }

        .tbl-h1 {
            font-size: 4mm;
            font-family: arial;
            border-radius: 6px;
            border-style: none;
            outline-style: none;
            background-color: darkslategray;
            font-weight: bold;
            color: white;
            width: 150px;


        }

        .txt-CV {
            color: white;
            font-family: arial;
            font-weight: bold;
            font-size: 5.5mm;
            padding: 20px;
            text-align: center;
            margin: 0;
        }

        nav {
            background: -webkit-linear-gradient(to right, #2B32B2, #1488CC);
            /* Chrome 10-25, Safari 5.1-6 */
            background: linear-gradient(to right, #2B32B2, #1488CC);
            /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */
            border-radius: 10px;

        }

        .txt-lnkS {
            font-size: 5mm;
            color: black;
            font-weight: bold;
            font-family: arial;
            text-decoration: none;
        }

        .lnk-A5 {
            color: #2B32B2;
            font-weight: bold;
            font-family: arial;

            font-size: 4mm;
        }
    </style>






</head>

<body>
    <article>
        <div class="div_customer">
            <nav>

                <h1 class="txt-CV">Settings</h1>


            </nav>
            <hr>

        </div>
        <article>

            <div class="div_customer">
                <a href="#" onclick="location.href='?page=admin'" class="txt-A1">&nbsp;<img src="<?php echo $config["IMG_PATH"] . 'backIcon.png'; ?>" style="width:35px; float:left;" alt=""></a>
                <br><br>
                <p class="txt-A2">User and Permission</p>

                <p class="txt-lnkS">Account</p>
                <p class="txt-Ch1">Admin:&nbsp;<?php echo $getAccountName;?></p>
                <a href="" class="lnk-A5">Manage Account</a>
                <br>
                <br>
                
                <a href="?page=logout" class="lnk-A5">Sign Out</a>
                <br> <br>
                <p class="txt-lnkS">Permission</p>
                <?php

                $getaccesscode  = "";
                $msg2  = "";
                $glink1 = "";

                while ($row = mysqli_fetch_array($result0)) {
                    $getaccesscode = $row["AccessCode"];
                }

                if ($_SESSION["access_code"] == $getaccesscode) {
                    $msg2 = '<b style="color:green;">Access Granted</b>';
                    $glink1 = '<input type="submit" class="lnk-A5" style="color:red; border-style:none; text-decoration:underline; cursor:pointer;" name="btn_deactivateCpanel"value="Deactivate Control Panel"/>';
                } else {
                    $msg2 = '<b style="color:red;">Access Denied</b>';
                    $glink1 = '<a href="?page=accesscode" class="lnk-A5" >Activate Control Panel</a>';
                }


                ?>
                <p class="txt-Ch1">Control Panel: &nbsp;<?php echo $msg2; ?> </p>
                <form action="?page=settings" method="post">

                <?php echo $glink1;?>
                
                </form>
                

            </div>

        </article>



    </article>
</body>

</html>