<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Log In</title>
</head>
<body>
    <h1>THIS IS LOGIN PAGE</h1>
    <br>
    <form action="?page=login" method="post">
        
        <input type="text" name="username_login" placeholder="Username">
        <input type="password" name="password_login" placeholder="Password">
        <input type="submit" name-"btnSubmit" value="Login">
        
        </form>


   

</body>
</html>
