<html> 
<link rel="stylesheet" href="<?php echo $config["LIBZ_PATH"]. 'css/style.css';?>">

<script>
        function openNav() {
  document.getElementById("mySidenav").style.width = "250px";
}

function closeNav() {
  document.getElementById("mySidenav").style.width = "0";
}

</script>
<nav>
<a href="#"  class="lnkC2"  > <span><img class="imgLogo" src="<?php echo $config["IMG_PATH"]. 'logo.png';?>" alt=""> &nbsp;</span> Vet Cooling System &nbsp;</a>

           
              <div style="float: right;">
              <img src="<?php echo $config["IMG_PATH"]. 'menuIcon.png';?>" alt="menu" class="menuIcon" onclick="openNav()" >
              </div>
             


<div id="mySidenav" class="sidenav">

  <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
  
            <a href="#" ><span> <img src="" alt="" > &nbsp;</span> Menu</a>
            <hr>

            <a href="?page=home" ><span>  &nbsp;</span> Home <img src="<?php echo $config["IMG_PATH"]. 'homeIcon.png';?>" class="icons" alt="" ></a>
            <a href="#"><span>  &nbsp;</span> Log In <img src="<?php echo $config["IMG_PATH"]. 'profileIcon.png';?>" class="icons" alt=""></a>
            <a href="#"><span>  &nbsp;</span> Sign Up <img src="<?php echo $config["IMG_PATH"]. 'accountnameIcon.png';?>" class="icons" alt=""></a>
            <a href="#" ><span>  &nbsp;</span> About<img src="<?php echo $config["IMG_PATH"]. 'aboutIcon.png';?>" class="icons"  alt=""></a>
            <a href="#" ><span> <img src="<?php echo $config["IMG_PATH"]. 'contactIcon.png';?>" class="icons" alt=""> &nbsp;</span> Contact Us</a>
            <a href="#" ><span> <img src="<?php echo $config["IMG_PATH"]. 'chatsupportIcon.png';?>" class="icons" alt=""> &nbsp;</span> Chat Support</a>
        

    
</div>
</nav>

</html>