<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="<?php echo $config["LIB_PATH"] . 'css' . DS . 'style.css'; ?>">
    <link rel="stylesheet" href="<?php echo $config["LIB_PATH"] . 'css' . DS . 'style1.css'; ?>">
    <script src="<?php echo $config["LIB_PATH"] . 'js' . DS . 'replacestate.js'; ?>"></script>

    <title>Database</title>

    <style>
        .tbl-h {
            font-size: 4mm;
            font-family: arial;
            border-radius: 6px;
            border-style: none;
            outline-style: none;
            background-color:  whitesmoke;
            font-weight: bold;
            color: black;
            width: 150px;


        }

        .tbl-h1 {
            font-size: 4mm;
            font-family: arial;
            border-radius: 6px;
            border-style: none;
            outline-style: none;
            background-color: darkslategray;
            font-weight: bold;
            color: white;
            width: 150px;
            cursor: pointer;


        }

        .txt-CV {
            color: white;
            font-family: arial;
            font-weight: bold;
            font-size: 5.5mm;
            padding: 20px;
            text-align: center;
            margin: 0;
        }

        nav {
            background: -webkit-linear-gradient(to right, #2B32B2, #1488CC);
            /* Chrome 10-25, Safari 5.1-6 */
            background: linear-gradient(to right, #2B32B2, #1488CC);
            /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */
            border-radius: 10px;

        }

        .txt-lnkS {
            font-size: 4.5mm;
            color: black;
            font-weight: bold;
            font-family: arial;
            text-decoration: none;
        }
    </style>

</head>

<body>

    <article>
        <div class="div_customer">
            <nav>
              
                <h1 class="txt-CV">Database</h1>
             

            </nav>
            <br>
            <a href="?page=admin" class="txt-lnkS">Admin</a>
            <hr>
            <center>
                <p class="txt-A2"></p>


                <span>
                    <form action="" method="post">
                        <p class="txt-A2">Fetch Data
                            <select name="data_fetch_name" id="" class="button-A">
                                <option value="Task Record">Task Record</option>
                                <option value="Inventory">Inventory</option>
                                <option value="Customer Account">Customer Account</option>
                                <option value="Employee Account">Employee Account</option>
                                <option value="Admin Account">Admin Acount</option>
                            </select>
                            <input type="submit" class="tbl-h1" value="Fetch" name="btn_fetch">

                    </form>
                </span>

                <br>

                </p>

            </center>

            <?php


            if ($_SESSION["database_fetch"] == $_SESSION["database_fetch"]) {

                echo '<p class="txt-A2">' . $_SESSION["database_fetch"] . ' <p>';
            }


            ?>

            <div class="div_form2">

                <table>





                    <?php


                    //task record
                    if ($_SESSION["database_fetch"] == "Task Record") {

                        echo '   <tr>
                            <th>
                                <input type="text" value="Id" class="tbl-h" readonly>
                            </th>
                            <th>
    
                                <input type="text" value="Customer Name" class="tbl-h" readonly>
                            </th>
                            <th>
    
                                <input type="text" value="Address" class="tbl-h" readonly>
                            </th>
                            <th>
    
                                <input type="text" value="  Contact Number" class="tbl-h" readonly>
                            </th>
                            <th>
    
                                <input type="text" value="  Problem Specification" class="tbl-h" readonly>
                            </th>
                            <th>
                                <input type="text" value="Scheduled Date" class="tbl-h" readonly>
                            </th>
                            <th>
                                <input type="text" value="Scheduled Time" class="tbl-h" readonly>
                            </th>
                            <th>
                                <input type="text" value="Pending" class="tbl-h" readonly>
                            </th>
                            <th>
                                <input type="text" value="Complete" class="tbl-h" readonly>
                            </th>
                            <th>
                                <input type="text" value="Cancel" class="tbl-h" readonly>
                            </th>
                            <th>
                                <input type="text" value="Control" class="tbl-h" readonly>
                            </th>
    
                        </tr>';
                        while ($row = mysqli_fetch_array($result1)) {
                            echo '<tr>';
                            echo '<td>';
                            echo '  <input type="text" value="' . $row["Id"] . '" class="tbl-h" readonly>';
                            echo '</td>';
                            echo '<td>';
                            echo '  <input type="text" value="' . $row["CustomerName"] . '" class="tbl-h" readonly>';
                            echo '</td>';
                            echo '<td>';
                            echo '  <input type="text" value="' . $row["Address"] . '" class="tbl-h" readonly>';
                            echo '</td>';
                            echo '<td>';
                            echo '  <input type="text" value="' . $row["ContactNumber"] . '" class="tbl-h" readonly>';
                            echo '</td>';
                            echo '<td>';
                            echo '  <input type="text" value="' . $row["ProblemSpecification"] . '" class="tbl-h" readonly>';
                            echo '</td>';
                            echo '<td>';
                            echo '  <input type="text" value="' . $row["Sched_Date"] . '" class="tbl-h" readonly>';
                            echo '</td>';
                            echo '<td>';
                            echo '  <input type="text" value="' . $row["Sched_Time"] . '" class="tbl-h" readonly>';
                            echo '</td>';
                            echo '<td>';
                            echo '  <input type="text" value="' . $row["Sched_Time"] . '" class="tbl-h" readonly>';
                            echo '</td>';
                            echo '<td>';
                            echo '  <input type="text" value="' . $row["Complete"] . '" class="tbl-h" readonly>';
                            echo '</td>';
                            echo '<td>';
                            echo '  <input type="text" value="' . $row["Cancel"] . '" class="tbl-h" readonly>';
                            echo '</td>';
                            echo '<td>';
                            echo '  <input type="submit" value="Details" class="tbl-h1" readonly>';
                            echo '</td>';
                            echo '</tr>';
                        }
                    }
                    //end task record



                    //task record
                    if ($_SESSION["database_fetch"] == "Admin Account") {

                        echo '   <tr>
                        <th>
                            <input type="text" value="Id" class="tbl-h" readonly>
                        </th>
                        <th>

                            <input type="text" value="Account Name" class="tbl-h" readonly>
                        </th>
                        <th>

                            <input type="text" value="Username" class="tbl-h" readonly>
                        </th>
                        <th>

                            <input type="text" value="Password" class="tbl-h" readonly>
                        </th>
                        <th>

                        <input type="text" value="Control" class="tbl-h" readonly>
                        </th>
                       

                    </tr>';
                        while ($row = mysqli_fetch_array($result2)) {
                            echo '<tr>';
                            echo '<td>';
                            echo '  <input type="text" value="' . $row["Id"] . '" class="tbl-h" readonly>';
                            echo '</td>';
                            echo '<td>';
                            echo '  <input type="text" value="' . $row["AccountName"] . '" class="tbl-h" readonly>';
                            echo '</td>';
                            echo '<td>';
                            echo '  <input type="text" value="' . $row["Username"] . '" class="tbl-h" readonly>';
                            echo '</td>';
                            echo '<td>';
                            echo '  <input type="text" value="' . $row["Password"] . '" class="tbl-h" readonly>';
                            echo '</td>';
                            echo '<td>';
                            echo '  <input type="submit" value="Details" class="tbl-h1" readonly>';
                            echo '</td>';
                            echo '</tr>';
                        }
                    }











                    ?>




                </table>

            </div>



        </div>

    </article>
</body>

</html>