<html>

<link rel="stylesheet" href="<?php echo $config["LIB_PATH"] . 'css' . DS . 'style.css'; ?>">
<link rel="stylesheet" href="<?php echo $config["LIB_PATH"] . 'css' . DS . 'style1.css'; ?>">
<script src="<?php echo $config["LIB_PATH"] . 'js' . DS . 'replacestate.js'; ?>"></script>
<script src="<?php echo $config["LIB_PATH"] . 'js' . DS . 'login.js'; ?>"></script>
<script>
  function openNav() {
    document.getElementById("mySidenav").style.width = "250px";
  }

  function closeNav() {
    document.getElementById("mySidenav").style.width = "0";
  }
</script>

<div class="body-A1">

  <div class="nav-A">

    <center>
      <a href="#" class="lnk-A"><span> <img src="<?php echo $config["IMG_PATH"] . 'menuIcon.png'; ?>" class="menuIcon1" alt="menu" onclick="openNav()"></span> Vet Cooling System <span> <img src="<?php echo $config["IMG_PATH"] . 'notification.png'; ?>" style="width:30px; float:right;" alt="menu"></span></a>
    </center>




    <div id="mySidenav" class="sidenav1">

      <a href="javascript:void(0)" class="closebtn1" onclick="closeNav()">&times;</a>

      <a href="#"><span> <img src="" alt=""> &nbsp;</span> Notification</a>
      <hr>


    </div>

  </div>




</div>



</html>